package com.dbcli.service;

import com.dbcli.model.MetricResult;

import java.util.List;

/**
 * Defines the contract for generating reports from metric results.
 * This interface allows for different report formats (e.g., Excel, HTML)
 * to be implemented and used interchangeably.
 */
public interface ReportGenerator {

    /**
     * Generates a report from a list of metric results and saves it to a specified path.
     *
     * @param results     The list of {@link MetricResult} objects to be included in the report.
     * @param outputPath  The directory path where the generated report should be saved.
     * @param metricsPath The path to the directory containing metric definition files,
     *                    which may be needed for context in the report.
     * @throws Exception if any error occurs during report generation.
     */
    void generate(List<MetricResult> results, String outputPath, String metricsPath) throws Exception;

    /**
     * Returns the specific format of the report generated by this implementation (e.g., "excel", "html").
     *
     * @return A string representing the report format.
     */
    String getFormat();
}